### PR TITLE
Pass `className` prop to container div

### PR DESCRIPTION
**Pull request by brahma-dev**

### CODE REVIEW

**Comment by Pauan** [comment]
Sorry for the delay, thanks for the pull request!

**Comment by brahma-dev** [comment]
@Pauan You seem to have removed the code that mattered.

**Comment by Pauan** [comment]
No, I did not. The `master` branch is for the old `1.x.x` version, the `3.x.x` branch is for the `3.x.x` version.

The changes you made are in the `3.1.0` version, which is published to npm.

**Comment by brahma-dev** [comment]
Sorry. I'd been working on the wrong branch.

**Comment by Pauan** [comment]
No problem, it's a very confusing system: normally `master` is where pull requests should be sent to.

The reason we aren't doing that is because some of our users are using GitHub directly (not npm), so we didn't want to break their code, so we had to create a new branch.

**Pull request merged**
